# Test Driven Model Development Using a Nice Sphere
Tim Tyree<br>
6.26.2020

In [1]:
import numpy as np, pandas as pd, matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D  

#automate the boring stuff
from IPython import utils
import time, os, sys, re
beep = lambda x: os.system("echo -n '\\a';sleep 0.2;" * x)
if not 'nb_dir' in globals():
    nb_dir = os.getcwd()
sys.path.append("../lib") 
from lib import *
sys.path.append("lib") 
from lib import *

# from operari import *
# from ProgressBar import *
# from mesh_ops import *

# the visualization tools involved here for triangular meshes is
import trimesh
import pyglet
from numba import njit, cuda
# from numba.typed import List
# import numba
import trimesh

#try using a scipy sparse matrix to speed up spring force evaluations
#TODO: speed up bigger meshes with pycuda's sparce matrices
from scipy.sparse import csr_matrix
import scipy.sparse as sparse

#formating
from matplotlib import rc
# rc('font',**{'family':'sans-serif','sans-serif':['Helvetica']})
## for Palatino and other serif fonts use:
#rc('font',**{'family':'serif','serif':['Palatino']})
# import matplotlib as mpl
# mpl.rcParams['font.size'] = 20
# mpl.rcParams['text.usetex'] = True
# mpl.rcParams['text.latex.preamble'] = r'\usepackage{{amsmath}}'
rc('text', usetex=True)

%autocall 1
%load_ext autoreload
%autoreload 2

Automatic calling is: Smart


# import the spherical mesh

In [2]:
os.chdir(f'{nb_dir}/Data/spherical_meshes')
mesh = trimesh.load('spherical_mesh_64.stl')
#subtract the center of mass
mesh.vertices -= mesh.center_mass
#normalize the mean radius to R
# R = 1. #unit length
# mesh.vertices *= R/np.mean(np.linalg.norm(mesh.vertices,axis=1))
mesh.vertices /= np.cbrt(mesh.volume*3/(4*np.pi))

face_normals all zero, ignoring!


In [3]:
assert(mesh.is_watertight)
assert(mesh.is_winding_consistent)

In [4]:
#unit length
print(np.mean(np.linalg.norm(mesh.vertices,axis=1)))
print(np.cbrt(mesh.volume*3/(4*np.pi)))

1.0083893459591489
1.0


In [11]:
#doesn't work. don't know why
# def mat_to_str(A):
#     string = f'''
#     {A[[0,0]]} & {A[[0,1]]} & {A[[0,2]]} & {A[[0,3]]} \\ 
#     {A[[1,0]]} & {A[[1,1]]} & {A[[1,2]]} & {A[[1,3]]} \\ 
#     {A[[2,0]]} & {A[[2,1]]} & {A[[2,2]]} & {A[[2,3]]} \\ 
#     {A[[3,0]]} & {A[[3,1]]} & {A[[3,2]]} & {A[[3,3]]} \\ 
#     '''
#     latex_string = r'$\left( \begin{array}{ll} ' + string + r'\end{{array}} \right)$'
#     return latex_string
# # text(my_matrix, (1,1))

# cast all vertices and shapes to quaternions in numpy. record as the undeformed surface
- TODO: dilate the sphere by a known amount
- TODO: compute the deformation gradient
- TODO: compute the 1st piola-kirchoff tensor for some constitutive relation
- TODO: taking thickness to be $\delta\ll1$, compute the effective surface tension, $\gamma$

In [20]:
from colorsys import hls_to_rgb

def colorize(z):
    n,m = z.shape
    c = np.zeros((n,m,3))
    c[np.isinf(z)] = (1.0, 1.0, 1.0)
    c[np.isnan(z)] = (0.5, 0.5, 0.5)

    idx = ~(np.isinf(z) + np.isnan(z))
    A = (np.angle(z[idx]) + np.pi) / (2*np.pi)
    A = (A + 0.5) % 1.0
    B = 1.0 - 1.0/(1.0+abs(z[idx])**0.3)
    c[idx] = [hls_to_rgb(a, b, 0.8) for a,b in zip(A,B)]
    return c

In [105]:
#define the constant pauli matrices as a basis for real space
sigx = 1.j*np.array([[0.,1.],[1.,0.]],dtype=complex)
sigy = 1.j*np.array([[0.,-1.j],[1.j,0.]],dtype=complex)
sigz = 1.j*np.array([[1.,0.],[0.,-1.]],dtype=complex)
one  = np.array([[1.,0.],[0.,1.]],dtype=complex)
zero = np.array([[0.,0.],[0.,0.]],dtype=complex)

#print the imaginary spatial basis, and test that identity and zero multiply correctly.
print(r'$\sigma_x is $')
print(sigx)
print(r'$\sigma_y is $')
print(sigy)
print(r'$\sigma_z is $')
print(sigz)
# print(one)
# print(zero)
# print((one.dot(sigx)))
assert((one.dot(sigx)==sigx).all())
assert((zero.dot(sigx)==zero).all())

# @njit
def vec_to_quaternion(v):
    #define the constant pauli matrices as a basis for real space
    #     sigx = np.array([[0.,1.],[1.,0.]],dtype=complex)
    #     sigy = np.array([[1.j,0.],[0.,-1.j]],dtype=complex)
    #     sigz = np.array([[1.,0.],[0.,-1.]],dtype=complex)
    return v[0]*sigx + v[1]*sigy + v[2]*sigz

$\sigma_x is $
[[0.+0.j 0.+1.j]
 [0.+1.j 0.+0.j]]
$\sigma_y is $
[[ 0.+0.j  1.-0.j]
 [-1.+0.j  0.+0.j]]
$\sigma_z is $
[[ 0.+1.j  0.+0.j]
 [ 0.+0.j -0.-1.j]]


In [112]:
#test the inverse of the basis elements are minus the basis elements
assert((np.linalg.inv(sigx)==-sigx).all())
assert((np.linalg.inv(sigy)==-sigy).all())
assert((np.linalg.inv(sigz)==-sigz).all())
#test the basis elements are anticommuting
assert((sigx*sigy-sigy*sigx==zero).all())
assert((sigx*sigz-sigz*sigx==zero).all())
assert((sigz*sigy-sigy*sigz==zero).all())


In [94]:
trim = mesh.triangles[0]
tris = mesh.triangles[100]

dm1 = trim[1]-trim[0]
dm2 = trim[2]-trim[0]
Am =  np.cross(dm1,dm2)/2

ds1 = tris[1]-tris[0]
ds2 = tris[2]-tris[0]
As =  np.cross(ds1,ds2)/2


qm1 = dm1[0]*sigx + dm1[1]*sigy + dm1[2]*sigz
qm2 = dm2[0]*sigx + dm2[1]*sigy + dm2[2]*sigz
qs1 = ds1[0]*sigx + ds1[1]*sigy + ds1[2]*sigz
qs2 = ds2[0]*sigx + ds2[1]*sigy + ds2[2]*sigz

qAm =  Am[0]*sigx + Am[1]*sigy + Am[2]*sigz
qAs =  As[0]*sigx + As[1]*sigy + As[2]*sigz

# solve for the deformation gradient between either pair of edges.
F1 = qs1.dot(np.linalg.inv(qm1))
F2 = qs2.dot(np.linalg.inv(qm2))
# FA = qAs.dot(np.linalg.inv(qAm))

In [95]:
#singular value decomposition on the block diagonal deformations
U1, S1, V1 = np.linalg.svd(F1)
V1 = V1.T.conjugate()

U2, S2, V2 = np.linalg.svd(F2)
V2 = V2.T.conjugate()

In [65]:
#verify svd is returning hermitian factors
assert((np.around(U1.dot(U1.T.conjugate()),3)==one).all())
assert((np.around(V1.dot(V1.T.conjugate()),3)==one).all())

In [54]:
Dm = np.array(((qm1,zero),(zero,qm2))).reshape((4,4))
Ds = np.array(((qs1,zero),(zero,qs2))).reshape((4,4))

In [55]:
#TODO: test if rotating by F maps dm to ds
F1.dot(qm1).dot(F1.conjugate().T)

array([[ 0.19636244+0.08863716j, -0.32928012+0.10565822j],
       [-0.32928012+0.10565822j, -0.19636244-0.08863716j]])

In [59]:
np.linalg.svd(Dm)

(array([[-4.55100762e-01+6.27258622e-01j,  2.63408971e-01-5.74495980e-01j,
          4.99331518e-18+2.45816952e-18j, -6.62242006e-33+1.35779811e-32j],
        [ 5.55111512e-17+7.17541049e-20j, -2.22044605e-16-4.69432513e-19j,
         -9.99997114e-01-2.40253579e-03j,  2.38779628e-16+7.61393059e-18j],
        [ 0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
          0.00000000e+00-5.91485583e-19j,  9.99911097e-01+1.33340620e-02j],
        [ 3.09556771e-01+5.51003197e-01j,  5.04924604e-01+5.87895592e-01j,
         -3.46982845e-17-4.77473646e-17j, -7.33510342e-33-7.18194059e-33j]]),
 array([4.16766413e-01, 2.42394003e-01, 2.23915350e-17, 1.66454779e-33]),
 array([[-0.5583836 +0.00000000e+00j, -0.22778082-3.69220336e-01j,
         -0.22778082-3.69220336e-01j,  0.5583836 +8.52418334e-18j],
        [-0.43382918+0.00000000e+00j,  0.29317777+4.75225248e-01j,
          0.29317777+4.75225248e-01j,  0.43382918+6.10693910e-17j],
        [ 0.60721645+0.00000000e+00j,  0.31540002+

In [46]:
#TODO: visualize F1 and F2 and see if they make sense.

TODO: matrix to quaternion

TODO: quaternion to matrix

In [68]:
sigy.T.conjugate()

array([[ 0.-1.j,  0.-0.j],
       [ 0.-0.j, -0.+1.j]])

In [71]:
sigy

array([[ 0.+1.j,  0.+0.j],
       [ 0.+0.j, -0.-1.j]])

# Handling Stress with quaternions only with nearly conformal mappings

Two deformations are conformal if their differentials are related by a rotation and a scaling.

$$d\tilde f = e^uRdf$$

Rotations represented in $\mathbb{R}^3$ require quadratic constraints which produce shear stress, which causes angles change under deformation.  The action of a quaternion on a vector can be written in terms of a rotation and a scale.

The shape of a triangle, which has six degrees of freedom in $\mathbb{R}^3$ cannot be represented by a single quaternion, which has only four degrees of freedom.  It is therefore necessary to represent the shape of a triangle with at least two quaternions, and it is sufficient to constrain those quaternions to be imaginary, since Im$\,\mathbb{H}\simeq\mathbb{R}^3$.

# Enter the basis of the triangle in real space only to compute deformation gradients that support shear stress

In [113]:
#TODO: copy the 'rotate into same plane solution' to a .py file
#TODO: rotate two triangles into the same plane
#TODO: scale so "the first" edge matches between the two triangles
#TODO: project all  edges onto the first vector using the outer product.  Test that the first vectors match. 
#TODO: for each second vector, compute the orthogonal component via the pythagorean theorem
#TODO: with 2 dimensional vectors in hand, plot some vectors on top of eachother in two different colors.
#TODO: use a shear deformation from the heisenburg group to make the triangles match
#TODO: test ^this by ploting a number of triangles.  do they all match?
#TODO: if so, congrats!  Collect the operations into one matrix.  congrats!  you can now measure the deformation gradient F!